### PR TITLE
Addition of new scenes

### PR DESCRIPTION
**Pull request by jordijoangimenez**
@nlsdvl @Etiennefaivredarcier, I have finally processed the selected scenes from Sketchfab. I'm not sure about the MPEG extensions added here when exporting. How do you know that? Because of the version of the rt-xr-blender-exporter?

### CODE REVIEW

**Comment by Etiennefaivredarcier** [comment]
Hello @jordijoangimenez , thank you for your commit. I don't see any extensions in the glTF file you provided. In the case you are talking about the MPEG_interactivity or anchoring extension, this should be done by hand (there is yet no tool to generate it). I can take care of this if needed.

**Comment by jordijoangimenez** [comment]
Hi @Etiennefaivredarcier, thanks. Do you see any of them? I ticked them when exporting according to https://youtu.be/bEMjw1YA78M?si=EzQsG6Pl4V0o0pcM
@nlsdvl, do we need extra instructions for interactivity and anchoring?

**Comment by jordijoangimenez** [comment]
I've agreed with @nlsdvl to have a look at this again today and will provide more comments before Friday. For the moment put this on hold.

**Comment by nlsdvl** [comment]
@jordijoangimenez the gltf seems to include the extensions as expected now, for instance : 

- https://github.com/5G-MAG/rt-xr-content/blob/62c3a97a385e3f30f44470381f0b8e45d1be7126/studio_apartment/studio_apartment.gltf#L10222
- https://github.com/5G-MAG/rt-xr-content/blob/62c3a97a385e3f30f44470381f0b8e45d1be7126/studio_apartment/studio_apartment.gltf#L23

**Comment by nlsdvl** [comment]
@jordijoangimenez  I reviewed and tested the assets. Here are my observations:

1. Guesthouse

This scene doesn't contain any MPEG extension. 
The scene is quite large (120MB+) is somewhat redundant with the `studio_appartment.gltf`,  do you intended to use both ? 


2. Studio appartment

The gltf document has MPEG media extensions, but the video files are missing.

I copied the media files from the `rt-xr-content/video` scene and the video playback worked as expected. We should avoid duplicating the same video files in each project if possible. Let's discuss this on our next call.

The texture in that scene is upside down. Is it upside down when you edit the scene in Blender ? If it is not the same orientation, then this sounds like a bug that needs to be reported.


3. 'Low poly' and 'post modern' furnitures 

As far I as understand, we want to start with a single item out of the furniture sets. I am working on this on my side to test the anchoring features.

**Comment by nlsdvl** [comment]
@jordijoangimenez - It appears the upside down texture is due to the Blender project being configured that way. 
In that case, the UV mapping of the texture should be fixed in Blender directly:
1. Select the mesh needs to be fixed, the one with the video texture applied to it.
2. Switch to the UV layout view, select the UV coordinates, right click on the texture UV mapping and use the mirror X/Y feature to fix the texture orientation 

upside-down-texture-1
upside-down-texture-2

**Pull request closed without merging**
