### PR TITLE
fix awards model scale & orientation

### PR DESCRIPTION
**Pull request by nlsdvl**
Fixes the scale of the academy award model to make it real life.

### CODE REVIEW

**Comment by jordijoangimenez** [comment]
Hi @nlsdvl , few things:
- The gltf with MPEG_anchor cannot be imported in Blender, right? MPEG_anchor is not supported?
- When importing the asset without extensions I get a buffer error: 
image

**Comment by jordijoangimenez** [comment]
Regarding the readme.md, it contains elements from the directory "geometry" is this intended or from a previous copy-paste? e.g. metadata/UseCase_02-variant3-geometry.jpg
## UseCase_03-variant1-geometry

**Comment by jordijoangimenez** [comment]
ok, I think the readme is incomplete. If we fix the issue when importing the glTF I can complete the readme myself.

**Comment by nlsdvl** [comment]
@jordijoangimenez Indeed the blender exporter doesn't support 'import' of MPEG extensions. This was out of scope of the initial blender development project.

It should be fairly easy to allow importing the document and ignore the extensions, but editing the MPEG_interactivity and MPEG_anchor extensions in blender is not planned at this point.

**Comment by nlsdvl** [comment]
Sorry about the README. I didn't realize it was not complete when I resumed work and pushed it. This is fixed now.

**Pull request merged**
